version: '2' # 表示该 Docker-Compose 文件使用的是 Version 2 file
services:
  docker-demo:  # 指定服务名称
    build: .  # 指定 Dockerfile 所在路径
    ports:    # 指定端口映射
      - "127.0.0.1:1234:80"
    image: zhe/glotozz
    environment:
      - FLAG=flag{Aurora}